### ISSUE TITLE
Third party miners reported as "old version"

### ISSUE THREAD

**Issue by colonelwatch** [Lulaschkas/duco-mining-dashboard#8]
I maintain nonceMiner, and one of its users reported in colonelwatch/nonceMiner#9 that this dashboard is reporting it as an "old version." Third party programs like mine should at least be exempt this message.

If it helps, nonceMiner does also report the version in its software name. As of May 29, the software name would be "nonceMiner v1.4.0".

**Comment by Lulaschkas** [comment]
Hi, sorry for the inconvenience the error should now not appear on non official miners. Thanks for noting!
